spring:
  application:
    name: customer
  profiles:
    active: production
eureka:
  client: ${eureka-client}
#accounts:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9999,localhost:9998
feign:
  hystrix:
    enabled: true